services:
  mongodb:
    image: mongodb/mongodb-atlas-local:8.2.0
    hostname: localhost
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 5s
      timeout: 5s
      retries: 10
